CI: azure
c_compiler: gcc
c_compiler_version: '12'
c_stdlib: sysroot
c_stdlib_version: '2.12'
cdt_name: cos6
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: quay.io/condaforge/linux-anvil-cos7-x86_64
extend_keys:
- pin_run_as_build
- extend_keys
- ignore_version
- ignore_build_only_deps
fortran_compiler: gfortran
giflib: '5.2'
ignore_build_only_deps:
- numpy
- python
libjpeg_turbo: '3'
libpng: '1.6'
libtiff: '4.6'
lua: '5'
numpy: '1.22'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.10'
r_base: '3.5'
target_platform: linux-64
zip_keys:
- - c_stdlib_version
  - cdt_name
