---
fail_fast: false
repos:
  #- repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    #  rev: v0.1.5
    # hooks:
      # Run the linter.
      # - id: ruff
      # args: [ --fix ]
      # Run the formatter.
      # - id: ruff-format
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
      - id: actionlint
