# For more information on how to use this template please refer to:
# https://tardis-sn.github.io/tardis/contributing/development/continuous_integration.html

name: mailmap

on:
  pull_request_target:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Check PR authors
        run: cat .mailmap | grep "$(git log $PR_BASE_SHA..HEAD --pretty='%aN <%aE>')"
        env:
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}

      - name: Error message
        run: |
          echo "Committer name or email couldn't be found in .mailmap"
          echo; git log $PR_BASE_SHA..HEAD --pretty='%aN <%aE>'
        if: failure()

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            *\*beep\* \*bop\**

            Hi, human.

            I'm the @tardis-bot and couldn't find your records in my database. I think we don't know each other, or you changed your credentials recently.

            Please add your **name** and **email** to `.mailmap` in your current branch and push the changes to this pull request.

            In case you need to map an existing alias, follow [this example](https://docs.enterprise.codescene.io/versions/2.0.0/getting-started/ensure-you-use-a-mailmap.html).
        if: failure()
