# For more information on how to use this template please refer to:
# http://tardis-sn.github.io/tardis/development/continuous_integration.html

name: update-changelog

on:
  schedule:
    - cron: '50 23 * * 0'

  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'tardis-sn' }}  # Do not run scheduled jobs on forks

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install github-changes
        run: sudo npm install -g github-changes

      - name: Update changelog
        run: github-changes -o tardis-sn -r tardis --only-pulls --use-commit-body -f CHANGELOG.md -k ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files
        run: |
          git config --local user.email "tardis.sn.bot@gmail.com"
          git config --local user.name "TARDIS Bot"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md [skip ci]"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_TOKEN }}  # Use BOT_TOKEN to push on write-protected branches
