# For more information on how to use this pipeline please refer to:
# http://tardis-sn.github.io/tardis/development/continuous_integration.html

trigger:
  - master

variables:
  codecov.token: 'a876d307-9ed5-4f5d-a6c4-e58291ac4111'
  system.debug: false

jobs:
  - job:
    pool:
      vmImage: $[variables.vm_Image]

    strategy:
      matrix:
        Linux:
          vm_Image: 'ubuntu-latest'

        macOS:
          vm_Image: 'macOS-latest'

      maxParallel: 2

    steps:
      - template: templates/default.yml
        parameters:
          fetchRefdata: true
          useMamba: true

      - bash: |
          cd $(tardis.dir)
          source activate tardis
          pip install pytest-azurepipelines
          pytest tardis --tardis-refdata=$(refdata.dir) --cov=tardis --cov-report=xml --cov-report=html
        displayName: 'TARDIS test'

      - bash: bash <(curl -s https://codecov.io/bash)
        displayName: 'Upload to codecov.io'
